stacklok/frizbee

pkg/ghactions/ghactions.go

The action list has the repo and the owner of the action, but the fact is that a repo
may hold more than one action at a time. To address this, this adds the actual action
string to the list, which should now hold a unique reference.

Add full action name in list

---

cmd/ghactions/list.go
go.mod
go.sum
pkg/ghactions/ghactions.go

I was being silly and did just appended blindly to a single slice which resulted in duplicates. Using a set seems like the cleanest option. On the API boundary, a plain slice is returned (I don't like returning 3rd party types from a public API..). There's also a new function to list all actions in a directory what I think the majority of users would like (except when parsing patches).

Use a set for the list to avoid duplicates

---

go.mod

This makes the library somewhat easier to use for consumers.

Only require x.y version of go, not x.y.z

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

This adds the relevant project information to the README, as well as a
code of conduct and contributing guidelines.
Closes: https://github.com/stacklok/frizbee/issues/5

Add README and project information

---

pkg/ghactions/ghactions.go

I was browsing the code and noticed that we'd re-written some code from the golang-set package.

Remove custom setAsSlice for ToSlice, switch to ThreadUnsafeSets

---

pkg/containers/containers_test.go

This replaces the `require` for `assert` to ease debugging, then it uses a more esoteric domain
for the test.
Closes #37

Fix flaky test

---

cmd/dockercompose/dockercompose.go
cmd/kubernetes/kubernetes.go
cmd/root.go
internal/cmd/doc.go
internal/cmd/yamlreplacer.go

These sub-commands are pretty much the same functionality as the `containerimage yaml`
sub-command. The main idea is that they are easier to figure out and type. The kubernetes
sub-command takes the "image regex" argument, which allows one to use an alternative
key to fetch a container image from a manifest. The `docker-compose` sub-command doesn't;
It'll just look for the `image` key in the YAML and attempt to replace that.

Add `kubernetes` and `docker-compose` sub-commands

---

pkg/ghactions/ghactions.go

This skips local references from the list sub-command, since these
are not relevant. We'll parse them anyway and output their inner actions
which is what we really care about.
We have a similar mechanism for the replacer piece of `ghactions`.
Closes: #39

`ghactions list`: skip local references from list

---

Taskfile.yml

This adds relevant description so doing `task -l` will list all targets and what they do.

Add descriptions to task targets

---

.github/workflows/test.yml

This is added to increase the rate limit of GitHub API calls.

Use GitHub token for doing frizbee CI check

---

cmd/ghactions/common.go
cmd/ghactions/ghactions.go
cmd/ghactions/one.go

This makes it easier to discover that this variable is possible to use.
The code now also has a constant to refer to this variable.

Output informaiton about the `GITHUB_TOKEN` env variable in relevant commands

---

pkg/config/config.go

This is handy for reading the configuration from a parsed repository.
e.g. as is the case in Minder.

Add utility function to parse frizbee configuration from a billy FS

---

pkg/ghactions/ghactions.go
pkg/ghactions/ghactions_test.go

Frizbee allowed to exclude the whole action name including the tag e.g. `actions/checkout@v4`. But this is not user-friendly for cases where the exclude would be upgraded over time as the exclude would have to be kept in sync.
Let's also support the case where the exclude is just in the form of `owner/action_name`.

Allow excluding just the action name

---

Taskfile.yml
cmd/root.go
cmd/version/version.go
pkg/constants/constants.go
pkg/containers/containers_test.go
pkg/containers/replace_test.go

add version subcommand for frizbee

---

pkg/ghactions/ghactions_test.go

This fixes the test to use the new checksum

Fix change in buf setup action checksum

---

cmd/root.go
cmd/version/version.go

This removes the usage of a global variable

Use version to return `version` sub-command

---

cmd/ghactions/list.go

This also adds validation for the `outputs` variable.

Remove globals from `ghactions list` subcommand

---

README.md

Adding [coverage link](https://coveralls.io/github/stacklok/frizbee) plus Apache / Discord badges to the README.

Add badges to frizbee

---

pkg/ghactions/ghactions.go

If the GitHub Action is already referenced via a commit or checksum, we
don't need to call GH to verify if it's a tag or a branch. This
effectively reduces the number of calls to GH to 0 in the best case.
Signed-off-by: Juan Antonio Osorio <ozz@stacklok.com>

GitHub Actions: Don't call GH API if action is already commit-referenced

---

pkg/ghactions/ghactions_test.go

Our tests use checkout@v4 which recently started pointing to 4.1.3.
Let's update the hashses.

Bump expected hashes of checkout@v4 to 4.1.3

---

pkg/ghactions/ghactions_test.go

The action's v1 got a new release recently:
https://github.com/bufbuild/buf-setup-action/commit/480a0ee8a588045b52a847b48138c6f377a89519

Bump the expected hash of buf-setup-action

---

go.mod
go.sum
pkg/replacer/actions/actions_test.go
pkg/replacer/replacer_test.go

Fixes one of the test references and bumps cobra and go-containerregistry.
Closes: #154 
Closes: #155

Fix unit test hash reference and bump cobra and go-containerregistry

---

pkg/replacer/replacer.go
pkg/replacer/replacer_test.go
pkg/utils/config/config.go

This provides a better backwards compatibility

Always ignore the scratch image even with an empty config

---

pkg/replacer/actions/actions_test.go
pkg/replacer/replacer_test.go

To make tests pass and have green CI.

Bump buf hashes again

---

.goreleaser.yaml

improve the release binary with linker flags `-s -w`, would shrink the binary by 1/3
```
$ go build -o frizbee_normal
$ ls -lh frizbee_normal
-rwxr-xr-x  1 rui  staff    18M Jul 15 14:10 frizbee_normal
$ go build -ldflags="-s -w" -o frizbee_stripped
$ ls -lh frizbee_stripped
-rwxr-xr-x  1 rui  staff    12M Jul 15 14:11 frizbee_stripped
```

chore: improve release binary

---

pkg/utils/config/config.go
pkg/utils/config/config_test.go

We used to ignore all actions that were referenced with a branch, but
this is not really intuitive. Let's only ignore main and master.
Relates: #175

Only ignore main and master, not all branches when pinning actions

---

README.md

This was left out from my previous patch

Fix the default configuration note in README

---

pkg/replacer/actions/actions_test.go
pkg/replacer/replacer_test.go

This uses an old action version in our tests, that is no longer receiving updates. This ensures that newer versions will not be released for this specific tag and the reference will always be the same.
The previously used action `actions/setup-node` received an update and no longer pointed to the same reference.

Use unchanging version tag in tests

---

.goreleaser.yaml

The following PR removes the part from goreleaser that pushes a custom formula to stacklok/tap. The reasoning is there's a upstream formula for frizbee in homebrew-core which we should continue to use.

Stop releasing a brew formula to stacklok/tap

---

pkg/replacer/actions/actions.go
pkg/replacer/replacer_test.go

The command `frizbee actions <action>@<tag>` incorrectly retrieves the tag's ref rather than the commit's one. The tag's ref should instead be used to retrieve the details of the tag, which contain the ref of the commit.
This change changes `getCheckSumForTag` to lookup the right field using two subsequent call to GitHub.
Fixes #206

Resolve commit ref correctly.

---

.goreleaser.yaml

The following PR temporarily disables publishing to winget. This broke because we migrated the winget-pkg repo to mindersec. 
Let's disable this for now so we can fix the release process and enable it after the holidays.

Temporarily disable publishing to winget

---

.golangci.yml
internal/cli/cli_test.go
internal/traverse/traverse_test.go
pkg/replacer/actions/actions_test.go
pkg/replacer/image/image_test.go
pkg/replacer/replacer_test.go
pkg/utils/config/config_test.go
pkg/utils/ghrest/ghrest_test.go
pkg/utils/store/cache_test.go

- chore(golangci): remove `go` version as it would default to go version in `go.mod`
- chore: replace deprecated `exportloopref` with `copyloopvar`

chore: update golangci-lint

---

.github/workflows/trivy.yml

This PR adds SARIF output format to the Trivy workflow and uses the upload-sarif action to upload the results to GitHub's security dashboard.

Add SARIF output and upload to Trivy workflow

---

pkg/replacer/actions/actions.go
pkg/replacer/actions/actions_test.go

When running frizbee against https://github.com/cloudnative-pg/cloudnative-pg I noticed that the output looked a bit funny:
```yaml
› frizbee actions list
+----+--------+------------------------------------------+-------------------------------------------+
| NO |  TYPE  |                   NAME                   |                    REF                    |
+----+--------+------------------------------------------+-------------------------------------------+
|  1 | action | 'google-github-actions/auth              | 6fc4af4b145ae7821d527454aa9bd537d1f2dc5f' |
|  2 | action | actions-cool/check-user-permission       | 7b90a27f92f3961b368376107661682c441f6103  |
|  3 | action | actions-ecosystem/action-add-labels      | 18f1af5e3544586314bbe15c0273249c770b2daf  |
[...]
```
As the `name` …

fix: strip quotes from uses field
